### ISSUE TITLE
tabs or spaces?

### ISSUE THREAD

**Issue by ashwin2802** [AerialRobotics-IITK/ros_best_practices#3]
tabs. cool?

**Comment by gajena** [comment]
Tabs usually take how many spaces?

**Comment by ashwin2802** [comment]
4

**Comment by ashwin2802** [comment]
this is actually a problem with python3 now. so need to guideline this well. ref:
https://stackoverflow.com/questions/5685406/inconsistent-use-of-tabs-and-spaces-in-indentation

**Comment by gajena** [comment]
I would suggest setting up editor with 2 space equal to one tab (for cpp), what do you say?

**Comment by ashwin2802** [comment]
logic?

**Comment by gajena** [comment]
Will get more code in less space.

**Comment by ashwin2802** [comment]
4 spaces per tabs by consensus.
